export { createDatabase, default } from "./connection.ts";
export type { ServerRow, ServerMetricSampleRow } from "./servers.ts";
export {
  getServers,
  getServer,
  getServerByProviderId,
  insertServer,
  updateServerStatus,
  updateServer,
  deleteServer,
  updateServerHostKey,
  recordServerObservation,
  insertServerMetricSample,
  getRecentServerMetrics,
  pruneOldServerMetrics,
} from "./servers.ts";
export type { BuildWorkerRow, BuildSourceRow } from "./build-workers.ts";
export {
  getBuildWorkers,
  getBuildWorker,
  getBuildWorkerByServerId,
  insertBuildWorker,
  updateBuildWorker,
  deleteBuildWorker,
  getBuildSource,
  getBuildSourceByRepository,
  getBuildSources,
  upsertBuildSource,
  updateBuildSourceDelivery,
  updateBuildSourceWorker,
  appsForBuildSource,
} from "./build-workers.ts";
export type { BuildWorkerLeaseRow } from "./build-worker-leases.ts";
export {
  BUILD_MIN_FREE_BYTES,
  BUILD_LEASE_TTL_SECONDS,
  BUILD_OBSERVATION_MAX_AGE_SECONDS,
  getBuildWorkerLeaseForOperation,
  getActiveBuildWorkerLease,
  listActiveBuildWorkerLeases,
  tryAcquireBuildWorkerLease,
  heartbeatBuildWorkerLease,
  releaseBuildWorkerLease,
  reapTerminalBuildWorkerLeases,
} from "./build-worker-leases.ts";
export type { BuildArtifactRow, BuildResultCheckpointRow } from "./build-artifacts.ts";
export {
  recordBuildArtifact,
  listBuildArtifacts,
  deleteBuildArtifacts,
  saveBuildResultCheckpoint,
  getBuildResultCheckpoint,
} from "./build-artifacts.ts";
export type {
  BuildSourceDeliveryRow,
  BuildSourceDeliveryStatus,
} from "./build-source-deliveries.ts";
export {
  BUILD_SOURCE_DELIVERY_STATUSES,
  getBuildSourceDelivery,
  getLatestBuildSourceDelivery,
  recordBuildSourceDelivery,
  attachBuildSourceDeliveryOperation,
  updateBuildSourceDeliveryStatus,
  listActiveBuildSourceDeliveries,
  listOlderQueuedBuildSourceDeliveries,
  markOlderBuildSourceDeliveriesSuperseded,
  compactBuildSourceDeliveries,
} from "./build-source-deliveries.ts";
export type { AppRow, AppIngressSettings, PublicProtocol, InternalProtocol } from "./apps.ts";
export {
  getApps,
  getApp,
  getAppByName,
  getAppByDomain,
  insertApp,
  insertAppWithFirstReplica,
  getServersForApp,
  hasRunningReplicas,
  updateAppStatus,
  requestAppRollout,
  clearAppRolloutRequest,
  markAppDeletionRequested,
  updateAppPublicEndpointStatus,
  updateAppDeployedBy,
  appendDeployLog,
  getDeployLog,
  deleteApp,
  updateAppEnvVars,
  updateAppContainerPort,
  updateAppArtifactAndHealth,
  updateAppImageRef,
  recordAppManifestApplied,
  updateAppStackManifestPath,
  updateAppBuildConfig,
  clearAppBuildConfig,
  normalizeAppConfigRevision,
  updateAppDomain,
  updateAppVolume,
  updateAppDesiredVolume,
  updateAppExtraVolumes,
  parseExtraVolumes,
  parseAppCommand,
  parseAppCapabilities,
  updateAppRuntimeOptions,
  updateAppMemory,
  updateAppCpu,
  updateAppAuthPassword,
  updateAppPublic,
  updateAppInternalProtocol,
  updateAppPlacement,
  setAppTarget,
  setAppStackNeeds,
  parseStackNeeds,
  getAppTargets,
  getStagingSibling,
  updateAppIngressSettings,
  updateAppEnvironment,
  getAppsByEnvironmentId,
  getAppsAffectedByEnvironment,
  markAppsEnvironmentStale,
  markAppsEnvironmentStaleForKeys,
  markAppEnvironmentFresh,
  nextReplicaHostPort,
  countApps,
  allocateInternalPort,
  INTERNAL_PORT_BASE,
  INTERNAL_PORT_COUNT,
  allocatePublicPort,
  getAppByPublicPort,
  updateAppPublicExposure,
  publicPortRange,
  PUBLIC_TCP_PORT_BASE,
  PUBLIC_TCP_PORT_COUNT,
  PUBLIC_UDP_PORT_BASE,
  PUBLIC_UDP_PORT_COUNT,
} from "./apps.ts";
export type { RetiredVolumeRow } from "./retired-volumes.ts";
export {
  retireVolume,
  getRetiredVolumes,
  getExpiredProvisionalVolumes,
  deleteRetiredVolume,
} from "./retired-volumes.ts";
export type { VolumeDeletionAuditRow } from "./volume-audit.ts";
export { beginVolumeDeletionAudit, finishVolumeDeletionAudit, getVolumeDeletionAudit } from "./volume-audit.ts";
export type { ReplicaRow, MetricSampleRow, ScalingEventRow } from "./replicas.ts";
export {
  insertReplica,
  getReplicas,
  getReplica,
  getReplicasByServer,
  updateReplicaStatus,
  recordReplicaAttestation,
  clearReplicaAttestation,
  updateReplicaMetrics,
  deleteReplica,
  getAllReplicas,
  touchReplicaHealth,
  incrementUnhealthyTicks,
  resetUnhealthyTicks,
  insertMetricSample,
  getRecentAppMetrics,
  getRecentMetricsByReplicas,
  pruneOldMetrics,
  insertScalingEvent,
  getScalingEvents,
} from "./replicas.ts";
export {
  reserveHostPort,
  releaseHostPortReservation,
  releaseHostPortReservations,
} from "./port-reservations.ts";
export type { DeploymentRow } from "./deployments.ts";
export {
  insertDeployment,
  updateDeploymentStatus,
  appendDeploymentLog,
  updateDeploymentGitCommit,
  updateDeploymentConfigRevision,
  updateDeploymentStorage,
  getDeployments,
  getDeployedCommit,
  getLastSuccessfulDeployment,
  gitCommitsMatch,
  getDeployment,
} from "./deployments.ts";
export type {
  UserRow,
  WebAuthnCredential,
  Permission,
  PermissionGrant,
  PermissionScope,
  ScopeType,
} from "./users.ts";
export {
  ALL_PERMISSIONS,
  SCOPABLE_PERMISSIONS,
  PERMISSION_SCOPES,
  scopeKindsFor,
  getUserGrants,
  getUserCount,
  getUserByUsername,
  getUserById,
  getUsers,
  insertUser,
  updateUserPassword,
  deleteUser,
  updateUserGitHub,
  clearUserGitHub,
  insertWebAuthnCredential,
  getWebAuthnCredentials,
  getWebAuthnCredentialById,
  updateWebAuthnCounter,
  deleteWebAuthnCredential,
  enableWebAuthn,
  disableWebAuthn,
  getWebAuthnCredentialCount,
  getUserPermissions,
  hasPermission,
  setUserPermissions,
  incrementTokenVersion,
} from "./users.ts";
export { getSettings, saveSetting } from "./settings.ts";
export type { PanelRow, PanelDeploymentRow } from "./panel.ts";
export {
  getPanel,
  insertPanel,
  updatePanelStatus,
  updatePanelEnvVars,
  appendPanelDeployLog,
  getPanelDeployLog,
  deletePanel,
  insertPanelDeployment,
  getPanelDeployments,
} from "./panel.ts";
export type { EnvironmentRow } from "./environments.ts";
export {
  getEnvironments,
  getEnvironment,
  getDeletedEnvironments,
  getDeletedEnvironment,
  insertEnvironment,
  updateEnvironment,
  deleteEnvironment,
  softDeleteEnvironment,
  restoreEnvironment,
  isEnvironmentPurgeProtected,
  duplicateEnvironment,
} from "./environments.ts";
export type { StackRow } from "./stacks.ts";
export {
  insertStack,
  getStack,
  getStackByName,
  getStacks,
  updateStackStatus,
  updateStackStagingEnvironment,
  updateStackStagingEnvKeys,
  appendStackLog,
  getStackLog,
  deleteStack,
  getAppsByStackId,
  setAppStack,
} from "./stacks.ts";
export type { AvailabilitySampleRow } from "./availability.ts";
export {
  computeMeetsTarget,
  currentAvailability,
  insertAvailabilitySample,
  getAvailabilityStats,
  pruneOldAvailabilitySamples,
} from "./availability.ts";
